language: r
sudo: required

r_github_packages:
  - datacamp/tutorial  # pre-install to avoid vignette package errors

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
