language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

r_github_packages:
  - datacamp/tutorial  # pre-install to avoid vignette package errors
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
